### ISSUE TITLE
Relative path in .classpath

### ISSUE THREAD

**Issue by gautemn** [ncabrera10/SolutionChecker_E-VRP#1]
First of all, thank you for making this. It really makes the life easier for those who are working on the E-VRP. 

Second, I would suggest using a relative path in .classpath, as it will make the process of using the code easier. 
I have very little experience with Java, but I think switching to  `<classpathentry kind="lib" path="./lib/jdom-2.0.6.1.jar"/>` will do the trick.

**Comment by ncabrera10** [comment]
Thank you for your suggestion. I made a change to the classpath file. It should work right now without the need of building the path locally. Please let me know if the change I made worked for you. 

Nicolás

**Comment by gautemn** [comment]
Thank you, it seems to work.
